#!/bin/bash
home=$(dirname $0)

sudo systemctl disable cloud-config
sudo systemctl disable cloud-final
sudo systemctl disable cloud-init-local
sudo systemctl disable cloud-init

exec_file=/opt/manage-cloud-init
service_name=manage-cloud-init.service
install -m 0755 -o root -g root $home/manage-cloud-init $exec_file

cat >/etc/systemd/system/${service_name}<<EOF
[Unit]
Description=Start cloud init services if MAC address match a pattern
After=network.service

[Service]
Type=oneshot
ExecStart=$exec_file

[Install]
WantedBy=multi-user.target
EOF

systemctl enable $service_name