#!/bin/bash

function user_add() {
    local username=$1
    local password=$2

    useradd $username
    echo -e $password | (passwd --stdin $username)
    install -m 0600 -o $username -g $username $home/key_rsa.pub /home/$username/.ssh/authorized_keys
    cat >>/etc/sudoers.d/${username}<<EOF
$username ALL=NOPASSWD: ALL
EOF
}

user_add localadmin ubuntu
user_add admin cisco123

# TODO: Move it to another place
sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config