#!/bin/bash
for iface in $(ip -o link | grep 'link/ether cc:' | cut -d ':' -f2)  # look for all ifaces with cc: as first octet of mac
do
    mac=$(ip l show  $iface | grep 'link/ether cc:' | cut -d ' ' -f6)
    IFS=':' octets=($mac)

    ip="${octets[1]}.${octets[2]}.${octets[3]}.${octets[4]}/${octets[5]}"
    echo sqe: Add $ip to $iface with $mac
    ip link set dev $iface up
    ip address add $ip dev $iface
done