#!/bin/bash
for int in $(ip -o link | grep -P -o '\d+: eth\d+' | awk '{print $2}')
do
    current_ip=$(ip address show $int | grep -P 'inet .*? scope' || true)
    if [ -n "$current_ip" ]
    then
        echo "sqe: IP $current_ip address is already assigned to $int interface"
        continue
    fi

    mac=$(ip address show $int | grep -P -o 'link/ether .*? brd' | awk '{print $2}')
    IFS=':' octets=($mac)

    # Assign IP address if MAC address looks like "XX:10:XX:XX:XX:XX"
    if [ ${octets[1]} = "10" ]
    then
        ip="${octets[2]}.${octets[3]}.${octets[4]}.${octets[5]}/24"
        echo "sqe: Add $ip to $int interface"
        ip link set dev $int up
        ip address add $ip dev $int
    else
        echo "sqe: Skip $int interface"
    fi
done