Folder: Automation itself tests
Title: Test VTS scenario
Description: VTS scenario creates number of networks and instances on these networks then ping all servers checking in parallel VTS responses to operations
UniqueID: os-sqe-dev03
PossibleDrivers: [vts]
Workers:
- class: lab.scenarios.vts_scenario.VtsScenario
  name: sce
  delay: 0
  run: 1
  pause: 0
  timeout: 360
  n_networks: 1
  n_servers: 2
  uptime: 30
  run_inside: ping
