Folder: Automation itself tests
Title: Test VTS disruptor
Description: Runs a number of VTS disruptors
UniqueID: os-sqe-dev02
PossibleDrivers: [vts]

Workers:

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtc-slave-shut
  delay: 0
  run: 1
  pause: 20
  node_to_disrupt: slave-vtc
  method_to_disrupt: vm-shutdown
  disrupt_time: 60
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtc-master-shut
  delay: [vtc-slave-shut]
  run: 1
  pause: 20
  node_to_disrupt: master-vtc
  method_to_disrupt: vm-shutdown
  disrupt_time: 60
  timeout: 1000


- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: slv-vtsr-mx
  delay: [vtc-master-shut]
  run: 1
  pause: 20
  node_to_disrupt: slave-vtsr
  method_to_disrupt: isolate-from-mx
  disrupt_time: 60
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: slv-vtsr-api
  delay: [slv-vtsr-mx]
  run: 1
  pause: 20
  node_to_disrupt: slave-vtsr
  method_to_disrupt: isolate-from-api
  disrupt_time: 60
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: slv-vtc-mx
  delay: [slv-vtsr-api]
  run: 1
  node_to_disrupt: slave-vtc
  method_to_disrupt: isolate-from-mx
  disrupt_time: 60
  pause: 20
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: slv-vtc-api
  delay: [slv-vtc-mx]
  run: 1
  node_to_disrupt: slave-vtc
  method_to_disrupt: isolate-from-api
  disrupt_time: 60
  pause: 20
  timeout: 1000
