Folder: Automation itself tests
Title: Force VTC switch master
Description: make sure that current master VTC disrupting indeed leads to switching to slave making it new master
UniqueID: os-sqe-dev06
PossibleDrivers: [vts]

Workers:

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: mx
  delay: 0
  run: 1
  node_to_disrupt: master-vtc
  method_to_disrupt: isolate-from-mx
  disrupt_time: 60
  pause: 20
  timeout: 1000

- class: lab.monitors.vts_monitor.VtsMonitor
  name: mon
  run: [mx]
  pause: 10
  delay: 0
  timeout: 360