Folder: Automation itself tests
Title: Test VTS disruptor
Description: Runs a number of VTS disruptors
UniqueID: os-sqe-dev02
PossibleDrivers: [vts]

Workers:

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtcSshut
  delay: 0
  run: 1
  pause: 20
  node_to_disrupt: slave-vtc
  method_to_disrupt: libvirt-suspend
  disrupt_time: 60
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtcMshut
  delay: [vtcSshut]
  run: 1
  pause: 20
  node_to_disrupt: master-vtc
  method_to_disrupt: libvirt-suspend
  disrupt_time: 60
  timeout: 1000


- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtsrSmx
  delay: [vtcMshut]
  run: 1
  pause: 20
  node_to_disrupt: slave-vtsr
  method_to_disrupt: isolate-from-mx
  disrupt_time: 60
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtcSmx
  delay: [vtsrSmx]
  run: 1
  node_to_disrupt: slave-vtc
  method_to_disrupt: isolate-from-mx
  disrupt_time: 60
  pause: 20
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtcSapi
  delay: [vtcSmx]
  run: 1
  node_to_disrupt: slave-vtc
  method_to_disrupt: isolate-from-api
  disrupt_time: 60
  pause: 20
  timeout: 1000
