Folder: Live Migration
Title: Live Migration
Description: Creates 2 large servers on single nework, start ping from first to second, does live migration, check ping suspends just for a while
UniqueID: os-sqe-lm01
PossibleDrivers: [vpp]

Workers:
- class: lab.scenarios.delete_scenario.DeleteScenario     # delete all created objects
  name: del0                                              # unique name
  delay: 0                                                # start immediately
  run: 1                                                  # run once
  delete: sqe                                             # delete sqe-* OS objects

- class: lab.scenarios.networks_scenario.NetworksScenario # create number of networks
  name: net                                               # unique name
  delay: [del0]                                           # delay until clenaup finish
  run: 1                                                  # run once
  uptime: forever                                         # just finish scenario after creation, leaving all networks forever
  timeout: 1000                                           # fail if not finished in 1000 secs
  n_networks: 1                                           # how many network

- class: lab.scenarios.servers_from_image_scenario.ServersFromImageScenario   # create number of servers
  name: srv                                               # unique name
  delay: [net]                                            # start after net is finished
  run: 1                                                  # run once
  uptime: forever                                         # and finish leaving all created servers forever
  n_servers: 2                                            # 2 servers
  flavor: m1.large
  image: sqe-iperf

- class: lab.scenarios.ping_scenario.PingScenario         # ping servers to make sure all is ok
  name: ping                                              # unique name
  delay: [srv]                                            # start after srv is finished
  run: [lm]                                               # run until lm finish
  n_packets: 200                                          # ping sends 200 packets
  how: internal                                           # ssh to the first server and ping the second one

- class: lab.scenarios.live_migration_scenario.LiveMigrationScenario
  name: lm                                                # unique name
  delay: [srv]                                            # delay until p1 is finished
  migration: live                                         # during cold migration ssh and pings will be lost
  run: 1                                                  # run once
