Folder: ha
Title: Passive VTC reboot while deleting OS servers
Description: Do OS instance create-ping-delete cycle, at the same time do passive vtc reboot in a cycle
UniqueID: os-sqe-vts04
PossibleDrivers: [vts]

Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: [VtsDisruptor]
  pause: 10
  timeout: 1000
  n_networks: 2
  n_servers: 10
  run_inside: ping
  uptime: 30

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 20
  run: 10
  pause: 10
  timeout: 1000
  node_to_disrupt: slave-vtc
  method_to_disrupt: vm-reboot
  disrupt_time: 120
