Folder: perf
Title: no CSR, 10 PVP chains with 1k flows
Description: runs number of perfomance benchmarks described in https://cisco.jiveon.com/docs/DOC-1711443. Target architecture is defined by pod on which this test is run.
UniqueID: os-sqe-perf09
PossibleDrivers: [vts, vpp]
Workers:
- class: lab.scenarios.ntt_scenario.NttScenario
  name: NttScenario
  delay: 0
  timeout: 1000
  run: 1
  run_inside: nfvbench  # might by nfvbench, csr, both
  csr_args: not-used
  nfvbench_args: --rate ndr_pdr --service-chain PVP --service-chain-count 10 --flow-count 1000 --frame-size 64 --frame-size IMIX --frame-size 1518

