Folder: ha
Title: Passive DL libvirt shutdown
Description: Do OS instance create-ping once then in the middle do passive dl vm shutdown then delete OS instance
UniqueID: os-sqe-vts07
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 20
  run: 1
  pause: 0
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 400

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 200
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: slave-vtsr
  method_to_disrupt: vm-shutdown
  run: 2
  disrupt_time: 20