Folder: ha
Title: Passive DL ncs stop
Description: Do OS instance create-ping once then in the middle do passive dl ncs stop then delete OS instance
UniqueID: os-sqe-vts05
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: [VtsDisruptor]
  pause: 0
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 400

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 200
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: slave-vtsr
  method_to_disrupt: ncs-stop
  disrupt_time: 20