Folder: ha
Title: Both VTC libvirt vm shutdown
Description: Do OS instance create-ping once then in the middle do both vtc vm shutdown then adding os vm then delete OS instance
UniqueID: os-sqe-vts18
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: mon
  delay: 0
  run: [sce]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: sce
  delay: [vtc_master, vtc_slave]
  run: 1
  pause: 0
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtc_master
  delay: 0
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: master-vtc
  method_to_disrupt: vm-shutdown
  disrupt_time: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: vtc_slave
  delay: [vtc_master]
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: slave-vtc
  method_to_disrupt: vm-shutdown
  disrupt_time: 20