Folder: ha
Title: Active VTC isolate XRNC from mx while adding OS servers
Description: Do OS instance create-ping-delete cycle, at the same time do active vtc xrnc isolate from mx in a cycle
UniqueID: os-sqe-vts17
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: [VtsDisruptorVtcMaster]
  pause: 10
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptorVtcMaster
  delay: 0
  run: 10
  pause: 10
  timeout: 1000
  node_to_disrupt: master-vtc
  method_to_disrupt: isolate-from-mx
  disrupt_time: 20
