Folder: ha
Title: Active VTC reboot while adding OS servers
Description: Do OS instance create-ping-delete cycle, at the same time do active vtc reboot in a cycle
UniqueID: os-sqe-vts20
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: mon
  delay: 0
  run: [sce]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: sce
  delay: 0
  run: [dis]
  pause: 10
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: dis
  delay: 0
  run: 3
  pause: 30
  timeout: 1000
  node_to_disrupt: master-vtc
  method_to_disrupt: vm-reboot
  disrupt_time: 20