Folder: ha
Title: Active VTC reboot while adding compute node
Description: Do compute node delete-add cycle, at the same time do active vtc reboot cycle
UniqueID: os-sqe-vts27
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: mon
  delay: 0
  run: [del_comp]
  pause: 2
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 0
  run: [del_comp, add_comp]
  pause: 20
  timeout: 1000
  disrupt_time: 60
  node_to_disrupt: master-vtc
  method_to_disrupt: vm-reboot

- class: lab.scenarios.vts_delete_compute.VtsDeleteCompute
  name: del_comp
  delay: 0
  run: 1
  pause: 100
  timeout: 1000

- class: lab.scenarios.vts_add_compute.VtsAddCompute
  name: add_comp
  delay: [del_comp]
  run: 1
  pause: 10
  timeout: 1000
