from lab.runners import Runner


class RunnerKloudBuster(Runner):

    def sample_config(self):
        return {'cloud': 'cloud name'}

    def __init__(self, config):
        super(RunnerKloudBuster, self).__init__(config=config)
        self.cloud_name = config['cloud']

    def execute(self, clouds, servers):
        cloud = clouds[0]
        server = servers[0]
        open_rc_body = cloud.create_open_rc()
        open_rc_path = '{0}.openrc'.format(self.cloud_name)
        results_path = '{0}_results.json'.format(self.cloud_name)
        venv_path = '~/venv_kloudbuster'

        server.create_user(new_username='kloudbuster')
        server.put(string_to_put=open_rc_body, remote_path=open_rc_path)
        repo_dir = server.clone_repo(repo_url='https://github.com/openstack/kloudbuster.git')
        server.run(command='virtualenv {0}'.format(venv_path))
        server.run(command='{0}/bin/pip install -r requirements.txt'.format(venv_path), in_directory=repo_dir)
        server.run(command='{0}/bin/python setup.py install'.format(venv_path), in_directory=repo_dir)
        status = server.run(command='{0}/bin/kloudbuster --tested-rc {1} --tested-passwd {2} --json {3}'.format(venv_path, open_rc_path, cloud.password, results_path))

        results = server.get(remote_path=results_path)

        with open('kloudbuster-results.txt', 'w') as f:
            f.write(status)
            f.write('\nJSON generated by kloudbuster:\n')
            f.write(results)

            f.write(self.get_artefacts(server=server))
